import pyttsx3
engine = pyttsx3.init()
engine.say("Hello world")
engine.say("We are fraternal eagles")
engine.say("We are representing each one of you.")
engine.say("The victim of this system. We are not the holly blood or a heavenly messenger.")
engine.say("So")
engine.say(" we are not compelling to following us. We have our on thoughts and rules.")
engine.say("we'll conquer the system with the old Hammurabis constitutions.")
engine.say("All we are is people who travel a short distance together")
engine.say("much like commuters who meet in a bus or train for a brief period of time . We have the same route")
engine.say("share a common.We are students")
engine.say("worker's.")
engine.say(" clerks. employed. And we're young and old")
engine.say("we where smart colleagues, activist and we come all raises country. And we're men")
engine.say("women")
engine.say("neighbor's drivers")
engine.say("network & administrators and Hacker's")
engine.say("programmer's")
engine.say("agents")
engine.say(" and sleeper cells")
engine.say("artist")
engine.say(" hacktivist.We have one things in common we never betrayed of fraternal orders.")
engine.say(" We're the army against the unsecured societies, nation, agencies and there forces.")
engine.say("We never collaborate our personal needs to this society. So do you want to join with us")
engine.say(" you needs to known this is not a party")
engine.say("community")
engine.say(" club or an revolution. we must need an action with hundred percent loyalty and honesty.")
robi = input("enter word ")
engine.say(robi)
engine.runAndWait()
